version: "3.9"
services:
  frontend:
    build: ./my-app
    ports:
      - "3000:3000"
    volumes:
      - ./react-app:/app
    depends_on:
      - backend
  backend:
    build: ./go-app
    ports:
      - "8080:8080"