version: "3.9"

services:
  go-app:
    build:
      context: ./go-app
    ports:
      - "8080:8080"
    volumes:
      - ./go-app/example.sqlite:/app/example.sqlite
    environment:
      - DATABASE_URL=example.sqlite

  react-app:
    build:
      context: ./react-app
    ports:
      - "3000:3000"