version: "3.9"

services:
  go-app:
    build:
      context: ./go-app
    ports:
      - "8080:8080"
    volumes:
      # - ./go-app/example.sqlite:/app/example.sqlite
      - ./go-app:/app/go
    #environment:
      #- DATABASE_URL=example.sqlite

  react-app:
    build:
      context: ./react-app
    ports:
      - "3000:3000"
  mysql:
    build:
      context: .
      dockerfile: ./database/Dockerfile
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: react-go-app
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/mysql_data:/var/lib/mysql
    ports:
    - 3306:3306
    links:
      - go-app